### ISSUE TITLE
TSDL_Palette.colors type issue

### ISSUE THREAD

**Issue by Raith** [ev1313/Pascal-SDL-2-Headers#23]
SDL2 wiki defines SDL_Palette.colors as "an array of SDL_Color structures representing the palette" while in the header it is just a pointer. I was doing some translations from C to pascal and I wasnt able to replicate the access to an array member as in colors[col]. I am not sure if this is my bad and if i should be first convering TSDL_Palette into a usable array first (or some other and easier way I am overlooking to access array elements) or it's an issue with the type.

**Comment by ev1313** [comment]
At least in FreePascal it should be possible acessing the pointer as array, see http://www.freepascal.org/docs-html/ref/refse15.html

I will look over it later, but iirc there're differences between Pascal and C arrays, so i cannot simply cast them together.

**Comment by Raith** [comment]
I should have mentioned that I am using delphi, this might be why I have this issue.

> Remark: Free Pascal treats pointers much the same way as C does. This means that a pointer to some type can be treated as being an array of this type.

I don't think I know how to achieve the same functionality in delphi (without reconstructing the array element by element) - for that however I need the pointer to at least the first element. I have since looked at surface.format.palette, which is always nil - the way you got the surface seems to be irrelevant (ie: ttf_rendertext_blended or SDL_CreateRGBSurface). The only time palette was not nil was if it was created with SDL_AllocPalette. Cant even get close to palette.colors

**Comment by ev1313** [comment]
Which Pixelformat do you use when creating the Surface? The palette is only set, if you use a format, which provides a palette (https://wiki.libsdl.org/SDL_PixelFormat).

When using SDL_CreateRGBSurface you need a bpp of 4 or 8 (https://wiki.libsdl.org/SDL_CreateRGBSurface)

**Comment by Raith** [comment]
I see. I'm creating surfaces with bpp higher than 4 or 8. And I dont specify any pixelformat otherwise. Both of those are gaps in my knowledge apparently, my own fault for not knowing why it is nil. It is highly possible that there's not problem with the type here, especially with {$POINTERMATH ON}.

I havent completed my translations so I cant confirm or deny that it wont cause any issues down the road, the code just covers all eventualities. The issue can probably be closed. Sorry for the commotion.
