### ISSUE TITLE
SDL_GetEventFilter defined incorectly

### ISSUE THREAD

**Issue by Imantsg** [ev1313/Pascal-SDL-2-Headers#24]
Original c code is 
SDL_bool SDL_GetEventFilter(SDL_EventFilter* filter, **void**** userdata)

Delphi definition is in sdlevents.inc is:

function SDL_GetEventFilter(filter: PSDL_EventFilter; userdata: **Pointer**): TSDL_Bool; cdecl;

right definition should be:
SDL_GetEventFilter = function(**out** filter: PSDL_EventFilter; **out** userdata: **PPointer**): TSDL_Bool cdecl;

** means that it is not a pointer but pointer to pointer and function is returning values so it should have at least out parameters.

I am not 100% sure about out parameters but I tested and it worked only if I used out parameters.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Shouldn't **var** instead of **out** do the trick as well? - Might be compatible with more compilers than just Delphi and ObjFPC. If you try it, let me know if it works, please.

**Comment by Imantsg** [comment]
I do not like "var" because compiler tend to give warnings that variable is not initialized. In case of "out" there are no such a warnings so I tend to use "out". But yes "var" did the trick too.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Thanks for the info. The issue got fixed by "var" now. Anyway, maybe 
"out" could be used for Delphi and ObjFPC by compiler directives in a 
further patch of the unit.


Am 02.02.2016 um 07:29 schrieb Imantsg:
