### ISSUE TITLE
Bug in SDL.pas C Macro conversions

### ISSUE THREAD

**Issue by mattsaintdev** [ev1313/Pascal-SDL-2-Headers#28]
Unit SDL.pas;

SDL_BITSPERPIXEL()
SDL_PIXELLAYOUT()
SDL_PIXELORDER()
SDL_PIXELTYPE()
SDL_PIXELFLAG()

Macro conversions are incorrect and should not return a bool but an Integer or Cardinal.

Further the Result should be AND'd with the mask not equated.

e.g of correct

Function SDL_BITSPERPIXEL(X: Cardinal): Cardinal;
Begin
  Result := (X Shr 8) And $FF;
End;

**Comment by Free-Pascal-meets-SDL-Website** [comment]
I agree. I made a minor patch addressing this. I wonder if you use these functions?
