### ISSUE TITLE
SDL audio callback doesn't work on Windows

### ISSUE THREAD

**Issue by bunnylin** [ev1313/Pascal-SDL-2-Headers#29]
The basic audio callback procedure works correctly on fpc/linux, but not on fpc/windows.

To fix, the definition of TSDL_AudioCallback in sdlaudio.inc:118 must be given the cdecl modifier.

(The TSDL_AudioFilter definition on line 138 probably needs cdecl too, though I didn't test that.)

**Comment by ev1313** [comment]
Fixed.
#
