### ISSUE TITLE
What OpenGL headers to use?

### ISSUE THREAD

**Issue by basisbit** [ev1313/Pascal-SDL-2-Headers#33]
what OpenGL headers do you suggest to use in combination with these Pascal-SDL-2-Headers?
I am currently using an own heavily modified version of the jedi-sdl headers but they only sorta work with up to OpenGL 2 stuff.
I also tried dglOpenGL headers but they use different types in many places so I was not able to hand over the opengl context from SDL_GL_CreateContext to be used by the dglOpenGL code.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
I'm not sure if the issue area is the right place to discuss these kind 
of questions.

As a hint, you may be interested in this article 
http://www.freepascal-meets-sdl.net/chapter-10-sdl-modern-opengl/ though.




Am 10.05.2016 um 22:38 schrieb basisbit:

**Comment by basisbit** [comment]
sorry, but that blog post is not really helpfull. to me it looks like you are using the compilers gl and glext units instead of the dglOpenGL and you only use stuff already available in the OpenGL 2 headers.
I am the developer of https://github.com/UltraStar-Deluxe/USDX and also recently switched to the Pascal-SDL-2-Headers. I wasn't able to get rid of the old jedi-sdl-opengl implementation (which is provided by freepascal compiler) and at the same time still use any glext or glu functions.
In my opinion this issue here in the project issue-tracker is the correct place to discuss about how to solve the problem that freepascal and Pascal-SDL-2-Headers are missing usable and somewhat current OpenGL headers.

**Comment by ev1313** [comment]
I used something like this (years ago):

`
constructor TEVOpenGLContext.Create(evwindow: TEVWindow; settings: TEVOpenGLContextSettings);
begin
  fWindow := evwindow;

  Log('Initializing OpenGL context', Info);

  SDL_GL_SetAttribute(SDL_GL_RED_SIZE, settings.red_size);
  SDL_GL_SetAttribute(SDL_GL_GREEN_SIZE, settings.green_size);
  SDL_GL_SetAttribute(SDL_GL_BLUE_SIZE, settings.blue_size);
  SDL_GL_SetAttribute(SDL_GL_ALPHA_SIZE, settings.alpha_size);
  SDL_GL_SetAttribute(SDL_GL_BUFFER_SIZE, settings.buffer_size);
  SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER, settings.double_buffer);
  SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE, settings.depth_size);
  SDL_GL_SetAttribute(SDL_GL_STENCIL_SIZE, settings.stencil_size);
  SDL_GL_SetAttribute(SDL_GL_ACCUM_RED_SIZE, settings.accum_red_size);
  SDL_GL_SetAttribute(SDL_GL_ACCUM_GREEN_SIZE, settings.accum_green_size);
  SDL_GL_SetAttribute(SDL_GL_ACCUM_BLUE_SIZE, settings.accum_blue_size);
  SDL_GL_SetAttribute(SDL_GL_ACCUM_ALPHA_SIZE, settings.accum_alpha_size);
  SDL_GL_SetAttribute(SDL_GL_STEREO, settings.stereo);
  SDL_GL_SetAttribute(SDL_GL_MULTISAMPLEBUFFERS, settings.multisamplebuffers);
  SDL_GL_SetAttribute(SDL_GL_MULTISAMPLESAMPLES, settings.multisamplesamples);
  SDL_GL_SetAttribute(SDL_GL_ACCELERATED_VISUAL, settings.accelerated_visual);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, settings.major_version);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, settings.minor_version);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_FLAGS, settings.flags);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, settings.profile_mask);
  SDL_GL_SetAttribute(SDL_GL_SHARE_WITH_CURRENT_CONTEXT,
                      settings.share_with_current_context);

  fContext := SDL_GL_CreateContext(fWindow.window);

  if fContext = nil then
  begin
    Log('Couldn''t initialize opengl context: ' + SDL_GetError(), Error);
    Free;
  end
  else
    Log('Successfully initialized opengl context.', Info);

  if(not InitializedOpenGL) then
  begin
    Log('Initializing OpenGL', Info);
    InitOpenGL;
    ReadExtensions;
    ReadImplementationProperties;
    InitializedOpenGL := true;
    if settings.flags = (settings.flags or SDL_GL_CONTEXT_DEBUG_FLAG) then
    begin
      glEnable(GL_DEBUG_OUTPUT);
      glDebugMessageCallback(@LogKHRDEBUG, nil);
    end;
  end;
end;`

**Comment by Free-Pascal-meets-SDL-Website** [comment]
I'm sorry if the article wasn't helpful. Seems I missed your point.

To me it is more like a general problem if Free Pascal is missing usable 
(stand-alone) OpenGL headers. At first sight, this is not necessarily 
related to SDL (therefore my remark about the place). I can now see your 
point of view though.  :-)

I'd appreciate to see if you can get dglOpenGL.pas get to work within 
your project. Good luck.

**Comment by basisbit** [comment]
in case someone else is searching for example code on how to get this working, feel free to take a look at https://github.com/UltraStar-Deluxe/USDX/blob/40076776ac5afca05bae90d6b4299f43c4923593/src/base/UGraphic.pas#L597
