### ISSUE TITLE
implementation  expected but ; found error in SDL2_net.pas

### ISSUE THREAD

**Issue by CrochetFeve0251** [ev1313/Pascal-SDL-2-Headers#34]
When i tried to build it i gave me that error : "SDL2_net.pas(335.150) Fatal: Syntx error, "IMPLEMENTATION" expected but ";" found "
Does i forget to do something before installing or there is a problem in the code?

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Hello,

I don't get an error loading this unit. Maybe you could share more details.
- Does it happen if you just include the unit in the uses clause?
- Did you change code in SDL2_net.pas?

**Comment by suve** [comment]
I'm guessing this may be because the line is terminated by a lonely semicolon. This generates an empty statement in the code, and a statement cannot appear in the Interface section.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
> I'm guessing this may be because the line is terminated by a lonely semicolon. This generates an empty statement in the code, and a statement cannot appear in the Interface section.

I missed that one. You are right and I guess this should fix the problem. 

@CrochetFeve0251: Maybe you could remove the very last semicolon in line 335 in SDL2_net.pas where it reads:

`function SDLNet_SocketReady(sock: TSDLNet_GenericSocket): Integer; {$IFNDEF DELPHI} inline; {$ELSE} {$IFDEF DELPHI10UP} inline; {$ENDIF} {$ENDIF};`

so it's becoming:

`function SDLNet_SocketReady(sock: TSDLNet_GenericSocket): Integer; {$IFNDEF DELPHI} inline; {$ELSE} {$IFDEF DELPHI10UP} inline; {$ENDIF} {$ENDIF}`

Please let us know, if it works.

**Comment by CrochetFeve0251** [comment]
It works for me without this semicolon thx for your help.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Thanks for your reply. Prepared a patch for this.
