### ISSUE TITLE
Bugs in sdlsyswm.inc

### ISSUE THREAD

**Issue by gr-pasc** [ev1313/Pascal-SDL-2-Headers#36]
There seem to be some differences between sdlsyswm.inc and SDL_syswm.h that cause problems.
1. The record __WMINFO_WINDOWS should be:
   
   __WMINFO_WINDOWS = record
     window: HWND; {**< The window handle *}
     hdc: HDC;     (**< The window device context *)
   end;

Instead, currently, it lacks the hdc field.
1. The record TSDL_SysWMinfo should start out like this:
   
   TSDL_SysWMinfo = record
     version: TSDL_version;
     subsystem: TSDL_SYSWM_TYPE;
     Case TSDL_SYSWM_TYPE of  
     ...

Instead, currently, no allocation is made for the subsystem field (which may or may not work out depending on field alignment)

**Comment by ev1313** [comment]
got atm no pascal compiler running and can't test it, can anyone create a (tested) pull request for this? else i'll fix it in a few days.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Struggle with time here, too, atm. On a short examination I also noticed 
that SDL_SYSWM_ANDROID seems to be missing in sdlsyswm.inc at SysWMinfo 
record:

{**
  *  The custom window manager information structure.
  *
  *  When this structure is returned, it holds information about which
  *  low level system it is using, and will be one of SDL_SYSWM_TYPE.
  *}
    PSDL_SysWMinfo = ^TSDL_SysWMinfo;
    TSDL_SysWMinfo = record
       version: TSDL_version;
       Case subsystem: TSDL_SYSWM_TYPE of
          (* Cannot have empty record case *)
          SDL_SYSWM_UNKNOWN: (dummy: sInt32);
          {$IFDEF SDL_VIDEO_DRIVER_WINDOWS}
             SDL_SYSWM_WINDOWS: (win : __WMINFO_WINDOWS);
          {$ENDIF}
          {$IFDEF SDL_VIDEO_DRIVER_WINRT}
             SDL_SYSWM_WINRT: (winrt : __WMINFO_WINRT);
          {$ENDIF}
          {$IFDEF SDL_VIDEO_DRIVER_X11}
             SDL_SYSWM_X11: (x11 : __WMINFO_X11);
          {$ENDIF}
          {$IFDEF SDL_VIDEO_DRIVER_DIRECTFB}
             SDL_SYSWM_DIRECTFB: (dfb : __WMINFO_DFB);
          {$ENDIF}
          {$IFDEF SDL_VIDEO_DRIVER_COCOA}
             SDL_SYSWM_COCOA: (cocoa : __WMINFO_COCOA);
          {$ENDIF}
          {$IFDEF SDL_VIDEO_DRIVER_UIKIT}
             SDL_SYSWM_UIKIT: (uikit : __WMINFO_UIKIT);
          {$ENDIF}
          {$IFDEF SDL_VIDEO_DRIVER_WAYLAND}
             SDL_SYSWM_WAYLAND: (wl : __WMINFO_WAYLAND);
          {$ENDIF}
          {$IFDEF SDL_VIDEO_DRIVER_MIR}
             SDL_SYSWM_MIR: (mir : __WMINFO_MIR);
          {$ENDIF}
    end;

**Comment by ev1313** [comment]
Is this structure defined in the header itself or only in the C source? if it's in the sources, then it's not necessary implementing it.

**Comment by gr-pasc** [comment]
This patch takes care of the original issue.

[sdlsyswm.inc.patch.txt](https://github.com/ev1313/Pascal-SDL-2-Headers/files/836298/sdlsyswm.inc.patch.txt)

**Comment by ev1313** [comment]
thanks to @gr-pasc fixed now #50
