### ISSUE TITLE
Missing field "last_fullscreen_flags" in TSDL_Window

### ISSUE THREAD

**Issue by tednilsen** [ev1313/Pascal-SDL-2-Headers#37]
Hi, first off... Thanks for the headers.

After getting some weird results (using SDL 2.0.4) in a TSDL_Window I was getting from SDL_CreateWindow, I discovered the TSDL_Window record was missing the "last_fullscreen_flags" field. Please see: [https://fossies.org/dox/SDL2-2.0.4/structSDL__Window.html](url)

So in sdlvideo.inc after the `flags: UInt32;` field, at line 60 please insert:
`last_fullscreen_flags: UInt32;`

The correct structure should now be:
`{* Define the SDL window structure, corresponding to toplevel windows *}`
`TSDL_Window = record`
`    magic: Pointer;`
`    id: UInt32;`
`    title: PAnsiChar;`
`    icon: PSDL_Surface;`
`    x,y: SInt32;`
`    w,h: SInt32;`
`    min_w, min_h: SInt32;`
`    max_w, max_h: SInt32;`
`    flags: UInt32;`
`    last_fullscreen_flags: UInt32;`
`    {* Stored position and size for windowed mode * }`
`    windowed: TSDL_Rect;`
`    fullscreen_mode: TSDL_DisplayMode;`
`    brightness: Float;`
`    gamma: PUInt16;`
`    saved_gamma: PUInt16;  {* (just offset into gamma) *}`
`    surface: PSDL_Surface;`
`    surface_valid: TSDL_Bool;`
`    shaper: PSDL_WindowShaper;`
`    data: PSDL_WindowUserData;`
`    driverdata: Pointer;`
`    prev: PSDL_Window;`
`    next: PSDL_Window;`
`  end;`

**Comment by Free-Pascal-meets-SDL-Website** [comment]
I crafted a quick patch to fix this issue. Thanks for reporting.

@Tim: I wondered when checking for the new field in struct of SDL_Window 
*in sdl_video.h* that I wasn't able to find it. It is located *in 
sdl_sysvideo.h*. Is this new (did they split the code into two files?) 
or did you merge the contents of these two files into sdlvideo.inc from 
the beginning? - Just out of curiosity.

**Comment by ev1313** [comment]
Yes, i splitted them apparently.
