### ISSUE TITLE
Linux jedi.inc compile problems

### ISSUE THREAD

**Issue by strangepapyrus** [ev1313/Pascal-SDL-2-Headers#42]
Haven't used this before and thought I'd try it out but it won't compile. Linux, Lazarus 1.6 FPC 3.0. Following error messages:

Compile Project, Target: chapter3: Exit code 256, Errors: 2, Warnings: 1
jedi.inc(55,4) Warning: Misplaced global compiler switch, ignored
jedi.inc(397,5) Error: Incompatible types: got "AnsiString" expected "Int64"
jedi.inc(397,5) Error: Compile time expression: Wanted Boolean but got <erroneous type> at IF or ELSEIF

Thanks.

**Comment by ev1313** [comment]
Should be fixed now.

**Comment by strangepapyrus** [comment]
Thank you. That's great. Compiles fine. :-)
