### ISSUE TITLE
Invalid TSDL_RendererFlip declaration

### ISSUE THREAD

**Issue by skalogryz** [ev1313/Pascal-SDL-2-Headers#44]
TSDL_RendererFlip type is declared as enumeration in pascal.
Which is not a good way to do, since in fact it should be used as set. 
Members of SDL_RendererFlip type are  expected to be used as bitwise operations: https://wiki.libsdl.org/SDL_RendererFlip
(It's possible to do SDL_FLIP_HORIZONTAL or SDL_FLIP_VERTICAL)

There're multiple ways to do that.

1. The safest way, is to declare TSDL_RenderFlipType as integer. Declare its members as  constants
Patch attached: [sdlrenderer.zip](https://github.com/ev1313/Pascal-SDL-2-Headers/files/721658/sdlrenderer.zip)

**WARN:** enums in C are integers, and should 32-bits. Enums are 32 bits in FPC, by default. They're packed in Delphi by default. Thus if an enumeration is part of a record, care must be taken when declaring alignment, since the final structure might end up be different, depending on the compiler used! 
(In this, the type is passed as a parameter, and it's not a big ise)

2. Add additional enumeration type, which would match the mask of SDL_FLIP_HORIZONTAL or SDL_FLIP_VERTICAL.

```
Index: sdlrenderer.inc
===================================================================
--- sdlrenderer.inc     (revision 159)
+++ sdlrenderer.inc     (working copy)
@@ -60,6 +60,7 @@
   TSDL_RendererFlip = (SDL_FLIP_NONE,       {**< Do not flip *}
                        SDL_FLIP_HORIZONTAL, {**< flip horizontally *}
                        SDL_FLIP_VERTICAL,    {**< flip vertically *}
+                       SDL_FLIP_DIAGONAL   {**< flip diagonally *}
                        );

   {**
```
However, that introduces a conflict with SDL headers and documentations (since they don't have SDL_FLIP_DIAGONAL constant)

3. Declare TSDL_RenderFlip as a set, which also introduces a difference between pascal and C headers.

**Comment by ev1313** [comment]
Noted, but got not enough time to merge atm. Thanks for the fix.

**Comment by ev1313** [comment]
Fixed.
