### ISSUE TITLE
Switch to GitLab? (MS bought GitHub)

### ISSUE THREAD

**Issue by Free-Pascal-meets-SDL-Website** [ev1313/Pascal-SDL-2-Headers#64]
No code issue. Should we consider switching to another hosting service (most prominent is https://about.gitlab.com/) because of Microsoft acquisition of GitHub (which isn't OpenSource anyway)? (https://blog.github.com/2018-06-04-github-microsoft/)

What do you think?

**Comment by ev1313** [comment]
In my opinion it won't make a difference, I don't care.

btw gitlab is hosted at MS: http://whois.domaintools.com/52.167.219.168

**Comment by bunnylin** [comment]
I'm in favor of moving as a matter of principle, but I'm just a user. :)

Gitlab's presently moving their stuff to Google cloud servers.

**Comment by ev1313** [comment]
Yeah, because Google is SOOOOO much better than Google ;)

**Comment by Free-Pascal-meets-SDL-Website** [comment]
I guess we can close this issue and should stay (for the moment :) .

Btw, thanks for merging #65.

**Comment by ev1313** [comment]
np, i thank you for your contributions Mathias!
