### ISSUE TITLE
Change license in accordance with SDL 2 library?

### ISSUE THREAD

**Issue by Free-Pascal-meets-SDL-Website** [ev1313/Pascal-SDL-2-Headers#66]
The SDL2 lib. has adopted the [zlib license](http://www.gzip.org/zlib/zlib_license.html). For best compatibility and wider spread usage of the units it may make sense to adopt this license for the SDL 2 units, too.

What do you think?

**Comment by Free-Pascal-meets-SDL-Website** [comment]
This is a good idea, since I think it would make them even more 
attractive. Both licenses complement each other in kind of a way 
(https://choosealicense.com/appendix/#trademark-use):

*Differences only:*

_Permissions: _

MPL: This license provides an express grant of patent rights from 
contributors.

zLib: This license explicitly states that it does NOT grant any rights 
in the patents of contributors.

_Conditions: _

MPL: Source code must be made available when the software is distributed.

_Limitations:_

MPL: This license explicitly states that it does NOT grant trademark 
rights, even though licenses without such a statement probably do not 
grant any implicit trademark rights.

(got information and statements from source link above)

**Comment by ev1313** [comment]
Done.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Thanks.


Am 30.07.2018 um 10:54 schrieb Tim Blume:
