### ISSUE TITLE
A small bug in sdl2_ttf.pas

### ISSUE THREAD

**Issue by scarsty** [ev1313/Pascal-SDL-2-Headers#68]
in sdl2_ttf.pas:

function TTF_RenderUNICODE_Blended(font: PTTF_Font; text: UInt16; fg: TSDL_Color): PSDL_Surface cdecl; external TTF_LibName {$IFDEF DELPHI} {$IFDEF MACOS} name '_TTF_RenderUNICODE_Blended' {$ENDIF} {$ENDIF};

the type of "text" should be PUint16

**Comment by ev1313** [comment]
fixed, thx.
